DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
    id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    tanggal_masuk DATE NOT NULL,
    no_hp VARCHAR(100) NOT NULL,
    limit_reimb VARCHAR(100) NOT NULL
    created_date DATE NOT NULL,
    updated_date DATE NOT NULL
);

--CREATE TABLE employee (
--    id INT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 0 MAXVALUE 100 ),
--    name VARCHAR(100) NOT NULL,
--    tanggal_masuk VARCHAR(100) NOT NULL,
--    no_hp VARCHAR(100) NOT NULL,
--    limit_reimb VARCHAR(100) NOT NULL
--);